import { describe, it, expect, vi, beforeEach } from 'vitest';
import { mkdtempSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { YarnProvider } from './YarnProvider';
import type { CacheService } from '../services/CacheService';

function createMockCacheService(overrides = {}): CacheService {
    return {
        isCacheValid: vi.fn().mockResolvedValue(false),
        readCache: vi.fn().mockResolvedValue(''),
        writeCache: vi.fn().mockResolvedValue(undefined),
        writePermanentCache: vi.fn().mockResolvedValue(undefined),
        hasPermanentCache: vi.fn().mockReturnValue(false),
        readPermanentCache: vi.fn().mockResolvedValue(undefined),
        getLastReleaseFetchHash: vi.fn().mockResolvedValue(undefined),
        setLastReleaseFetchHash: vi.fn().mockResolvedValue(undefined),
        hasLockfileChangedSinceLastFetch: vi.fn().mockResolvedValue(true),
        ...overrides,
    } as unknown as CacheService;
}

// Sample yarn.lock content matching Yarn Berry v4 format
const sampleYarnLock = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10c0

"react@npm:^18.0.0":
  version: 18.2.0
  resolution: "react@npm:18.2.0"
  checksum: 10c0-abc123
  languageName: node
  linkType: hard

"vitest@npm:^4.0.0":
  version: 4.0.0
  resolution: "vitest@npm:4.0.0"
  checksum: 10c0-def456
  languageName: node
  linkType: hard

"jest@npm:^29.0.0":
  version: 29.0.0
  resolution: "jest@npm:29.0.0"
  checksum: 10c0-ghi789
  languageName: node
  linkType: hard

"@myapp/shared@workspace:packages/shared":
  version: 0.0.0-use.local
  resolution: "@myapp/shared@workspace:packages/shared"
  languageName: unknown
  linkType: soft
`;

function writeSampleRepo(dir: string): void {
    writeFileSync(
        join(dir, 'package.json'),
        JSON.stringify({
            name: 'my-monorepo',
            version: '0.0.0',
            workspaces: ['packages/*'],
            dependencies: {
                react: '^18.0.0',
            },
            devDependencies: {
                vitest: '^4.0.0',
            },
        }),
    );
    writeFileSync(join(dir, 'yarn.lock'), sampleYarnLock);

    // Create workspace package
    const webDir = join(dir, 'packages', 'web');
    mkdirSync(webDir, { recursive: true });
    writeFileSync(
        join(webDir, 'package.json'),
        JSON.stringify({
            name: '@myapp/web',
            version: '1.0.0',
            dependencies: {
                react: '^18.0.0',
                '@myapp/shared': 'workspace:*',
            },
            devDependencies: {
                jest: '^29.0.0',
            },
        }),
    );
}

describe('YarnProvider', () => {
    let tmpDir: string;

    beforeEach(() => {
        vi.clearAllMocks();
        tmpDir = mkdtempSync(join(tmpdir(), 'yarn-provider-test-'));
        writeSampleRepo(tmpDir);
    });

    describe('getPackages', () => {
        it('parses yarn.lock to PackageInfo[] format', async () => {
            const cacheService = createMockCacheService();
            const provider = new YarnProvider(cacheService, tmpDir);

            const packages = await provider.getPackages();

            // Root package
            const root = packages.find((p) => p.name === 'my-monorepo');
            expect(root).toBeDefined();
            expect(root!.version).toBe('0.0.0');
            expect(root!.dependencies).toEqual({
                react: {
                    from: 'react',
                    version: '18.2.0',
                    resolved: '',
                    path: '',
                },
            });
            expect(root!.devDependencies).toEqual({
                vitest: {
                    from: 'vitest',
                    version: '4.0.0',
                    resolved: '',
                    path: '',
                },
            });
        });

        it('caches in memory on subsequent calls', async () => {
            const cacheService = createMockCacheService();
            const provider = new YarnProvider(cacheService, tmpDir);

            const first = await provider.getPackages();
            const second = await provider.getPackages();

            expect(first).toBe(second);
        });

        it('includes workspace packages', async () => {
            const cacheService = createMockCacheService();
            const provider = new YarnProvider(cacheService, tmpDir);

            const packages = await provider.getPackages();

            const workspace = packages.find((p) => p.name === '@myapp/web');
            expect(workspace).toBeDefined();
            expect(workspace!.version).toBe('1.0.0');
            expect(workspace!.dependencies).toEqual({
                react: {
                    from: 'react',
                    version: '18.2.0',
                    resolved: '',
                    path: '',
                },
            });
            expect(workspace!.devDependencies).toEqual({
                jest: {
                    from: 'jest',
                    version: '29.0.0',
                    resolved: '',
                    path: '',
                },
            });

            // Root + 1 workspace = 2 total packages
            expect(packages).toHaveLength(2);
        });

        it('skips workspace: references in dependencies', async () => {
            const cacheService = createMockCacheService();
            const provider = new YarnProvider(cacheService, tmpDir);

            const packages = await provider.getPackages();

            const workspace = packages.find((p) => p.name === '@myapp/web');
            expect(workspace!.dependencies).not.toHaveProperty('@myapp/shared');
        });

        it('handles scoped packages in resolved versions', async () => {
            const lockContent = `__metadata:
  version: 8
  cacheKey: 10c0

"@octokit/rest@npm:^22.0.0":
  version: 22.0.1
  resolution: "@octokit/rest@npm:22.0.1"
  checksum: 10c0-abc
  languageName: node
  linkType: hard
`;
            writeFileSync(join(tmpDir, 'yarn.lock'), lockContent);
            writeFileSync(
                join(tmpDir, 'package.json'),
                JSON.stringify({
                    name: 'test-repo',
                    version: '1.0.0',
                    workspaces: ['packages/*'],
                    dependencies: {
                        '@octokit/rest': '^22.0.0',
                    },
                }),
            );

            const cacheService = createMockCacheService();
            const provider = new YarnProvider(cacheService, tmpDir);
            const packages = await provider.getPackages();

            expect(packages[0]!.dependencies!['@octokit/rest']!.version).toBe('22.0.1');
        });

        it('handles multiple specifiers for same package', async () => {
            const lockContent = `__metadata:
  version: 8
  cacheKey: 10c0

"semver@npm:^7.3.5, semver@npm:^7.7.3, semver@npm:^7.7.4":
  version: 7.7.4
  resolution: "semver@npm:7.7.4"
  checksum: 10c0-abc
  languageName: node
  linkType: hard
`;
            writeFileSync(join(tmpDir, 'yarn.lock'), lockContent);
            writeFileSync(
                join(tmpDir, 'package.json'),
                JSON.stringify({
                    name: 'test-repo',
                    version: '1.0.0',
                    workspaces: ['packages/*'],
                    dependencies: {
                        semver: '^7.7.4',
                    },
                }),
            );

            const cacheService = createMockCacheService();
            const provider = new YarnProvider(cacheService, tmpDir);
            const packages = await provider.getPackages();

            expect(packages[0]!.dependencies!['semver']!.version).toBe('7.7.4');
        });

        it('handles workspaces as object with packages key', async () => {
            writeFileSync(
                join(tmpDir, 'package.json'),
                JSON.stringify({
                    name: 'my-monorepo',
                    version: '0.0.0',
                    workspaces: { packages: ['packages/*'] },
                    dependencies: {
                        react: '^18.0.0',
                    },
                }),
            );

            const cacheService = createMockCacheService();
            const provider = new YarnProvider(cacheService, tmpDir);
            const packages = await provider.getPackages();

            expect(packages).toHaveLength(2);
            expect(packages.find((p) => p.name === '@myapp/web')).toBeDefined();
        });
    });

    describe('isInCatalog', () => {
        it('always returns false (yarn has no catalog feature)', () => {
            const cacheService = createMockCacheService();
            const provider = new YarnProvider(cacheService, tmpDir);

            expect(provider.isInCatalog('react', '18.2.0')).toBe(false);
            expect(provider.isInCatalog('vitest', '4.0.0')).toBe(false);
        });
    });

    describe('hasInCatalog', () => {
        it('always returns false (yarn has no catalog feature)', () => {
            const cacheService = createMockCacheService();
            const provider = new YarnProvider(cacheService, tmpDir);

            expect(provider.hasInCatalog('react')).toBe(false);
            expect(provider.hasInCatalog('anything')).toBe(false);
        });
    });

    describe('isPatched', () => {
        it('returns false when no patches exist', () => {
            const cacheService = createMockCacheService();
            const provider = new YarnProvider(cacheService, tmpDir);

            expect(provider.isPatched('react', '18.2.0')).toBe(false);
        });

        it('detects user-applied patch: protocol entries', () => {
            const lockContent = `__metadata:
  version: 8
  cacheKey: 10c0

"lodash@npm:^4.17.21":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"
  checksum: 10c0-abc
  languageName: node
  linkType: hard

"lodash@patch:lodash@npm%3A4.17.21#./.yarn/patches/lodash-npm-4.17.21-abc123.patch":
  version: 4.17.21
  resolution: "lodash@patch:lodash@npm%3A4.17.21#./.yarn/patches/lodash-npm-4.17.21-abc123.patch::version=4.17.21&hash=abc123"
  languageName: node
  linkType: hard
`;
            writeFileSync(join(tmpDir, 'yarn.lock'), lockContent);

            const cacheService = createMockCacheService();
            const provider = new YarnProvider(cacheService, tmpDir);

            expect(provider.isPatched('lodash', '4.17.21')).toBe(true);
            expect(provider.isPatched('react', '18.2.0')).toBe(false);
        });

        it('does not flag builtin optional patches as user patches', () => {
            const lockContent = `__metadata:
  version: 8
  cacheKey: 10c0

"typescript@npm:^5.9.3":
  version: 5.9.3
  resolution: "typescript@npm:5.9.3"
  checksum: 10c0-abc
  languageName: node
  linkType: hard

"typescript@patch:typescript@npm%3A^5.9.3#optional!builtin<compat/typescript>":
  version: 5.9.3
  resolution: "typescript@patch:typescript@npm%3A5.9.3#optional!builtin<compat/typescript>::version=5.9.3&hash=abc"
  languageName: node
  linkType: hard
`;
            writeFileSync(join(tmpDir, 'yarn.lock'), lockContent);

            const cacheService = createMockCacheService();
            const provider = new YarnProvider(cacheService, tmpDir);

            expect(provider.isPatched('typescript', '5.9.3')).toBe(false);
        });
    });
});
