name: Publish

on:
    release:
        types: [published]

permissions:
    contents: read
    id-token: write

jobs:
    publish:
        runs-on: ubuntu-latest
        environment: Publish
        steps:
            - uses: actions/checkout@v4
            - uses: jdx/mise-action@v2
            - run: pnpm install
            - run: pnpm run build
            - name: Publish to NPM
              run: pnpm publish --no-git-checks --provenance ${{ github.event.release.prerelease && '--tag rc' || '' }}
